/* eslint-disable react/no-unescaped-entities */
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/NPv3UIxlfWW
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";

import { useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";

export function Docs() {
  const [isOpen, setIsOpen] = useState(false);
  return (
    <div className="flex min-h-screen w-full">
      <aside
        className={`fixed inset-y-0 left-0 z-10 flex w-64 flex-col border-r bg-background p-4 transition-all duration-300 ${
          isOpen ? "translate-x-0" : "-translate-x-full"
        } sm:translate-x-0 sm:flex`}
      >
        <div className="mb-6 flex items-center gap-2">
          <BookIcon className="h-6 w-6" />
          <h1 className="text-xl font-semibold">Documentation</h1>
        </div>
        <nav className="flex flex-col gap-2">
          <Link
            href="#"
            className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-muted hover:text-foreground focus:bg-muted focus:text-foreground"
            prefetch={false}
          >
            <HomeIcon className="h-4 w-4" />
            Introduction
          </Link>
          <Link
            href="#"
            className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-muted hover:text-foreground focus:bg-muted focus:text-foreground"
            prefetch={false}
          >
            <LayersIcon className="h-4 w-4" />
            Getting Started
          </Link>
          <Link
            href="#"
            className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-muted hover:text-foreground focus:bg-muted focus:text-foreground"
            prefetch={false}
          >
            <CodeIcon className="h-4 w-4" />
            Components
          </Link>
          <Link
            href="#"
            className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-muted hover:text-foreground focus:bg-muted focus:text-foreground"
            prefetch={false}
          >
            <CompassIcon className="h-4 w-4" />
            Theming
          </Link>
          <Link
            href="#"
            className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-muted hover:text-foreground focus:bg-muted focus:text-foreground"
            prefetch={false}
          >
            <BookOpenIcon className="h-4 w-4" />
            API Reference
          </Link>
          <Link
            href="#"
            className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-muted hover:text-foreground focus:bg-muted focus:text-foreground"
            prefetch={false}
          >
            <CircleHelpIcon className="h-4 w-4" />
            Support
          </Link>
        </nav>
      </aside>
      <div className="flex-1 p-8 sm:pl-64">
        <div className="mx-auto max-w-3xl">
          <div className="mb-8">
            <h1 className="text-3xl font-bold">Introduction</h1>
            <p className="mt-2 text-muted-foreground">
              Welcome to the documentation for our amazing product. Here you'll
              find everything you need to get started and make the most of our
              features.
            </p>
          </div>
          <div className="space-y-8">
            <section>
              <h2 className="text-2xl font-semibold">Getting Started</h2>
              <p className="mt-2 text-muted-foreground">
                Follow these steps to set up your account and start using our
                product.
              </p>
              <div className="mt-4 space-y-4">
                <div className="rounded-md border bg-muted p-4">
                  <h3 className="text-lg font-semibold">Step 1: Sign Up</h3>
                  <p className="mt-2 text-muted-foreground">
                    Visit our website and click the "Sign Up" button to create
                    your account.
                  </p>
                </div>
                <div className="rounded-md border bg-muted p-4">
                  <h3 className="text-lg font-semibold">
                    Step 2: Verify Email
                  </h3>
                  <p className="mt-2 text-muted-foreground">
                    Check your inbox for the verification email and click the
                    link to activate your account.
                  </p>
                </div>
                <div className="rounded-md border bg-muted p-4">
                  <h3 className="text-lg font-semibold">
                    Step 3: Set Up Profile
                  </h3>
                  <p className="mt-2 text-muted-foreground">
                    Complete your profile by adding your personal information
                    and preferences.
                  </p>
                </div>
              </div>
            </section>
            <section>
              <h2 className="text-2xl font-semibold">Components</h2>
              <p className="mt-2 text-muted-foreground">
                Explore the various components available in our library and how
                to use them.
              </p>
              <div className="mt-4 space-y-4">
                <div className="rounded-md border bg-muted p-4">
                  <h3 className="text-lg font-semibold">Button</h3>
                  <p className="mt-2 text-muted-foreground">
                    The Button component is used for triggering actions. It
                    supports various styles and sizes.
                  </p>
                </div>
                <div className="rounded-md border bg-muted p-4">
                  <h3 className="text-lg font-semibold">Card</h3>
                  <p className="mt-2 text-muted-foreground">
                    The Card component is used for displaying content in a
                    structured way.
                  </p>
                </div>
                <div className="rounded-md border bg-muted p-4">
                  <h3 className="text-lg font-semibold">Input</h3>
                  <p className="mt-2 text-muted-foreground">
                    The Input component is used for collecting user input.
                  </p>
                </div>
              </div>
            </section>
            <section>
              <h2 className="text-2xl font-semibold">Theming</h2>
              <p className="mt-2 text-muted-foreground">
                Customize the appearance of your application by adjusting the
                theme.
              </p>
              <div className="mt-4 space-y-4">
                <div className="rounded-md border bg-muted p-4">
                  <h3 className="text-lg font-semibold">Color Palette</h3>
                  <p className="mt-2 text-muted-foreground">
                    Our theme provides a comprehensive color palette that you
                    can use to style your application.
                  </p>
                </div>
                <div className="rounded-md border bg-muted p-4">
                  <h3 className="text-lg font-semibold">Typography</h3>
                  <p className="mt-2 text-muted-foreground">
                    Customize the font styles and sizes to match your brand's
                    visual identity.
                  </p>
                </div>
                <div className="rounded-md border bg-muted p-4">
                  <h3 className="text-lg font-semibold">Spacing</h3>
                  <p className="mt-2 text-muted-foreground">Lorem ipsum</p>
                </div>
              </div>
            </section>
          </div>
        </div>
      </div>
      <Button
        variant="outline"
        size="icon"
        className="fixed top-4 left-4 z-20 sm:hidden"
        onClick={() => setIsOpen(!isOpen)}
      >
        <VolumeXIcon className="h-6 w-6" />
        <span className="sr-only">Toggle sidebar</span>
      </Button>
    </div>
  );
}

function BookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
    </svg>
  );
}

function BookOpenIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z" />
      <path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z" />
    </svg>
  );
}

function CircleHelpIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3" />
      <path d="M12 17h.01" />
    </svg>
  );
}

function CodeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>
  );
}

function CompassIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m16.24 7.76-1.804 5.411a2 2 0 0 1-1.265 1.265L7.76 16.24l1.804-5.411a2 2 0 0 1 1.265-1.265z" />
      <circle cx="12" cy="12" r="10" />
    </svg>
  );
}

function HomeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  );
}

function LayersIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83Z" />
      <path d="m22 17.65-9.17 4.16a2 2 0 0 1-1.66 0L2 17.65" />
      <path d="m22 12.65-9.17 4.16a2 2 0 0 1-1.66 0L2 12.65" />
    </svg>
  );
}

function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  );
}

function VolumeXIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5" />
      <line x1="22" x2="16" y1="9" y2="15" />
      <line x1="16" x2="22" y1="9" y2="15" />
    </svg>
  );
}
