/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ucwLu3o6dWI
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import { ResponsiveLine } from "@nivo/line"

export function TokenView() {
  return (
    <div className="min-h-screen bg-[#0F172A] text-white">
      <header className="flex items-center justify-between p-6 border-b border-[#334155]">
        <div className="flex items-center space-x-6">
          <div className="text-[#6366F1] font-bold text-2xl">Uniswap</div>
          <nav className="flex space-x-6">
            <a href="#" className="text-[#94A3B8] hover:text-white transition-colors">
              Trade
            </a>
            <a href="#" className="text-white transition-colors">
              Explore
            </a>
            <a href="#" className="text-[#94A3B8] hover:text-white transition-colors">
              Pool
            </a>
          </nav>
        </div>
        <div className="flex items-center space-x-6">
          <input
            type="text"
            placeholder="Search tokens and NFT collections"
            className="bg-[#334155] text-white px-4 py-2 rounded-full w-72 focus:outline-none focus:ring-2 focus:ring-[#6366F1]"
          />
          <button className="bg-[#6366F1] text-white px-6 py-2 rounded-full hover:bg-[#4F46E5] transition-colors">
            Connect
          </button>
        </div>
      </header>
      <main className="p-8">
        <div className="flex space-x-8">
          <div className="flex-1">
            <div className="flex items-center space-x-6 mb-6">
              <div className="bg-[#F59E0B] rounded-full w-12 h-12" />
              <div>
                <h1 className="text-3xl font-bold">Dai DAI</h1>
                <p className="text-[#94A3B8]">0x6B17...d0F</p>
              </div>
            </div>
            <div className="flex items-center space-x-6 mb-6">
              <h2 className="text-4xl font-bold">$1.00</h2>
              <p className="text-[#22C55E]">+0.01%</p>
            </div>
            <div className="bg-[#334155] p-6 rounded-lg mb-6">
              <LineChart className="w-full h-[400px]" />
              <div className="flex justify-between mt-6">
                <div className="flex space-x-4">
                  <button className="bg-[#475569] text-white px-6 py-2 rounded-full hover:bg-[#94A3B8] transition-colors">
                    1H
                  </button>
                  <button className="bg-[#475569] text-white px-6 py-2 rounded-full hover:bg-[#94A3B8] transition-colors">
                    1D
                  </button>
                  <button className="bg-[#475569] text-white px-6 py-2 rounded-full hover:bg-[#94A3B8] transition-colors">
                    1W
                  </button>
                  <button className="bg-[#475569] text-white px-6 py-2 rounded-full hover:bg-[#94A3B8] transition-colors">
                    1M
                  </button>
                  <button className="bg-[#475569] text-white px-6 py-2 rounded-full hover:bg-[#94A3B8] transition-colors">
                    1Y
                  </button>
                </div>
                <button className="bg-[#475569] text-white px-6 py-2 rounded-full hover:bg-[#94A3B8] transition-colors">
                  Price
                </button>
              </div>
            </div>
            <div className="mb-6">
              <h2 className="text-2xl font-bold mb-4">Stats</h2>
              <div className="grid grid-cols-4 gap-6">
                <div>
                  <p className="text-[#94A3B8]">TVL</p>
                  <h3 className="text-3xl font-bold">$132.6M</h3>
                </div>
                <div>
                  <p className="text-[#94A3B8]">Market cap</p>
                  <h3 className="text-3xl font-bold">$5.3B</h3>
                </div>
                <div>
                  <p className="text-[#94A3B8]">FDV</p>
                  <h3 className="text-3xl font-bold">$5.3B</h3>
                </div>
                <div>
                  <p className="text-[#94A3B8]">1 day volume</p>
                  <h3 className="text-3xl font-bold">$11.3M</h3>
                </div>
              </div>
            </div>
            <div>
              <h2 className="text-2xl font-bold mb-4">Transactions</h2>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Time</TableHead>
                    <TableHead>Type</TableHead>
                    <TableHead>$DAI</TableHead>
                    <TableHead>For</TableHead>
                    <TableHead>USD</TableHead>
                    <TableHead>Wallet</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow>
                    <TableCell>55s ago</TableCell>
                    <TableCell className="text-[#22C55E]">Buy</TableCell>
                    <TableCell>2,910.73</TableCell>
                    <TableCell>1.16 ETH</TableCell>
                    <TableCell>$2,911.53</TableCell>
                    <TableCell>0xD1Fa...0cB7</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>4m ago</TableCell>
                    <TableCell className="text-[#EF4444]">Sell</TableCell>
                    <TableCell>2,991.00</TableCell>
                    <TableCell>2,991.04 USDT</TableCell>
                    <TableCell>$2,991.02</TableCell>
                    <TableCell>0xcde6...1546</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>5m ago</TableCell>
                    <TableCell className="text-[#22C55E]">Buy</TableCell>
                    <TableCell>50,397.35</TableCell>
                    <TableCell>50,402.00 USDC</TableCell>
                    <TableCell>$50,400.00</TableCell>
                    <TableCell>0x3ec9...219f</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>6m ago</TableCell>
                    <TableCell className="text-[#22C55E]">Buy</TableCell>
                    <TableCell>2,910.73</TableCell>
                    <TableCell>1.16 ETH</TableCell>
                    <TableCell>$2,911.53</TableCell>
                    <TableCell>0xD1Fa...0cB7</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>7m ago</TableCell>
                    <TableCell className="text-[#EF4444]">Sell</TableCell>
                    <TableCell>2,991.00</TableCell>
                    <TableCell>2,991.04 USDT</TableCell>
                    <TableCell>$2,991.02</TableCell>
                    <TableCell>0xcde6...1546</TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </div>
          </div>
          <div className="w-96">
            <div className="bg-[#334155] p-6 rounded-lg mb-6">
              <div className="flex justify-between mb-6">
                <button className="bg-[#475569] text-white px-6 py-2 rounded-full hover:bg-[#94A3B8] transition-colors">
                  Swap
                </button>
                <button className="bg-[#475569] text-white px-6 py-2 rounded-full hover:bg-[#94A3B8] transition-colors">
                  Limit
                </button>
                <button className="bg-[#475569] text-white px-6 py-2 rounded-full hover:bg-[#94A3B8] transition-colors">
                  Send
                </button>
                <button className="bg-[#475569] text-white px-6 py-2 rounded-full hover:bg-[#94A3B8] transition-colors">
                  Buy
                </button>
              </div>
              <div className="flex justify-between mb-6">
                <button className="bg-[#475569] text-white px-6 py-2 rounded-full hover:bg-[#94A3B8] transition-colors">
                  50%
                </button>
                <button className="bg-[#475569] text-white px-6 py-2 rounded-full hover:bg-[#94A3B8] transition-colors">
                  Settings
                </button>
              </div>
              <div className="flex flex-col space-y-6">
                <div className="flex items-center justify-between">
                  <p>Sell</p>
                  <p>0</p>
                </div>
                <button className="bg-[#F59E0B] text-[#0F172A] px-6 py-2 rounded-full hover:bg-[#D97706] transition-colors">
                  Select token
                </button>
                <div className="flex items-center justify-between">
                  <p>Buy</p>
                  <p>0</p>
                </div>
                <button className="bg-[#475569] text-white px-6 py-2 rounded-full hover:bg-[#94A3B8] transition-colors">
                  DAI
                </button>
                <button className="bg-[#F59E0B] text-[#0F172A] px-6 py-2 rounded-full hover:bg-[#D97706] transition-colors">
                  Connect wallet
                </button>
              </div>
            </div>
            <div className="bg-[#334155] p-6 rounded-lg">
              <h2 className="text-2xl font-bold mb-6">Info</h2>
              <div className="flex items-center space-x-6 mb-6">
                <p>0x6B17...d0F</p>
                <button className="bg-[#475569] text-white px-6 py-2 rounded-full hover:bg-[#94A3B8] transition-colors">
                  Etherscan
                </button>
              </div>
              <div className="flex items-center space-x-6 mb-6">
                <button className="bg-[#475569] text-white px-6 py-2 rounded-full hover:bg-[#94A3B8] transition-colors">
                  Website
                </button>
                <button className="bg-[#475569] text-white px-6 py-2 rounded-full hover:bg-[#94A3B8] transition-colors">
                  Twitter
                </button>
              </div>
              <p className="text-[#94A3B8]">
                MakerDAO has launched Multi-collateral DAI (MCD). This token refers to the new DAI that is
                collateralized by multiple assets.
              </p>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}

function LineChart(props) {
  return (
    <div {...props}>
      <ResponsiveLine
        data={[
          {
            id: "Desktop",
            data: [
              { x: "Jan", y: 43 },
              { x: "Feb", y: 137 },
              { x: "Mar", y: 61 },
              { x: "Apr", y: 145 },
              { x: "May", y: 26 },
              { x: "Jun", y: 154 },
            ],
          },
          {
            id: "Mobile",
            data: [
              { x: "Jan", y: 60 },
              { x: "Feb", y: 48 },
              { x: "Mar", y: 177 },
              { x: "Apr", y: 78 },
              { x: "May", y: 96 },
              { x: "Jun", y: 204 },
            ],
          },
        ]}
        margin={{ top: 10, right: 10, bottom: 40, left: 40 }}
        xScale={{
          type: "point",
        }}
        yScale={{
          type: "linear",
        }}
        axisTop={null}
        axisRight={null}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 5,
          tickPadding: 16,
        }}
        colors={["#2563eb", "#e11d48"]}
        pointSize={6}
        useMesh={true}
        gridYValues={6}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        role="application"
      />
    </div>
  )
}
