/* eslint-disable @next/next/no-img-element */
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/577WDcRkVN0
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Gabarito } from 'next/font/google'

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card } from "@/components/ui/card";
import Link from "next/link";

export function TokenCard() {
  return (
    <Card className="bg-background rounded-xl overflow-hidden shadow-lg w-full">
      <Link href="/token-page" prefetch={false}>
        <div className="flex items-center justify-between px-6 py-4 border-b">
          <div className="flex items-center gap-4">
            <img
              src="/placeholder.svg"
              alt="Token Logo"
              className="w-10 h-10 rounded-full"
              width="40"
              height="40"
              style={{ aspectRatio: "40/40", objectFit: "cover" }}
            />
            <div className="overflow-hidden">
              <h3 className="text-lg font-semibold whitespace-nowrap overflow-hidden text-ellipsis transition-all duration-300">
                Uniswap
              </h3>
              <p className="text-sm text-muted-foreground">UNI</p>
            </div>
          </div>
          <div className="text-sm text-muted-foreground mt-2">$1.23B</div>
        </div>
        <div className="p-6">
          <p className="text-muted-foreground">
            Uniswap is a decentralized exchange (DEX) that allows for
            peer-to-peer cryptocurrency trading without a central authority.
          </p>
        </div>
      </Link>
      <div className="px-6 pb-6">
        <div className="flex items-center gap-4 mt-4">
          <Link
            href="#"
            className="text-primary hover:underline"
            prefetch={false}
          >
            <TwitterIcon className="w-5 h-5" />
          </Link>
          <Link
            href="#"
            className="text-primary hover:underline"
            prefetch={false}
          >
            <TextIcon className="w-5 h-5" />
          </Link>
          <Link
            href="#"
            className="text-primary hover:underline"
            prefetch={false}
          >
            <GlobeIcon className="w-5 h-5" />
          </Link>
        </div>
      </div>
    </Card>
  );
}

function GlobeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20" />
      <path d="M2 12h20" />
    </svg>
  );
}

function TextIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17 6.1H3" />
      <path d="M21 12.1H3" />
      <path d="M15.1 18H3" />
    </svg>
  );
}

function TwitterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  );
}
